### ISSUE TITLE
How long to run for?

### ISSUE THREAD

**Issue by tfppcn** [Paperspace/DinoRunTutorial#13]
Hi, I managed to get the code running and have used CPU only to train it. Below are the runtime result. How long do I have to run it for to observe any improvement in training? 
FYI, I ran this code on my surface pro 3 i5 for about 20 hours or so.

<img width="814" alt="01playgame" src="https://user-images.githubusercontent.com/57092490/100527227-9c742180-3224-11eb-9bc7-9c74db8e3052.png">

<img width="662" alt="02score" src="https://user-images.githubusercontent.com/57092490/100527235-ad249780-3224-11eb-930b-9bc9247b2b9c.png">

<img width="675" alt="03maxscore" src="https://user-images.githubusercontent.com/57092490/100527236-b150b500-3224-11eb-8dc0-abb974155ea4.png">

<img width="568" alt="04q_max" src="https://user-images.githubusercontent.com/57092490/100527250-d5ac9180-3224-11eb-9fc2-ca43e9920924.png">

**Comment by ravi72munde** [comment]
Hi, I understand that you have used CPU to run the training. I've used a GPU for the experiment after realizing that the CPU just won't cut it. I barely got to 100 on CPU on my previous attempt. This repo has configurations which are suitable for GPU system as it involves a lot more calculations. A CPU would take a longer time to do that same calculations and would in turn miss few important frames captures, making the training unstable and highly variable. I'd recommend going with a GPU system(which also takes a lot of time).
