### ISSUE TITLE
init_cache() not working 

### ISSUE THREAD

**Issue by StefanJanuschke** [Paperspace/DinoRunTutorial#5]
I set up the ML-in-a-Box, machine on Paperspace. 
Unfortunately when I run init_cache() get the following error: 

`FileNotFoundError: [Errno 2] No such file or directory: 'objects/epsilon.pkl`

**Comment by StefanJanuschke** [comment]
Same holds true if I run it on my Windows machine.

**Comment by StefanJanuschke** [comment]
I copy/pasted the objects folder from your other DinoRun GitHub folder, works now. 
Not sure if this is intentional and I just missed something.

**Comment by RubenSikkes** [comment]
I think the solution is to just create an objects folder ;)
