### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'objects/D.pkl'

### ISSUE THREAD

**Issue by tkgmomosheep** [Paperspace/DinoRunTutorial#6]
I am experiencing the above the error when I run the command, I copied the objects folder to the directory already. I am running it on windows 10 and the chrome browser did pop up and the game started but in the command prompt shows the error below. 

`C:\Users\Tom\Desktop\Chrome-Dino-Reinforcement-Learning-master\DinoRunTutorial-master>jupyter nbconvert --execute "Reinforcement Learning Dino Run.ipynb"
[NbConvertApp] Converting notebook Reinforcement Learning Dino Run.ipynb to html
[NbConvertApp] Executing notebook with kernel: python3

DevTools listening on ws://127.0.0.1:64177/devtools/browser/b0ad5ad8-8ca7-44f6-a4fa-7a1de1a2553e
[NbConvertApp] ERROR | Error while converting 'Reinforcement Learning Dino Run.ipynb'
Traceback (most recent call last):
  File "c:\users\tom\appdata\local\programs\python\python36\lib\site-packages\nbconvert\nbconvertapp.py", line 407, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "c:\users\tom\appdata\local\programs\python\python36\lib\site-packages\nbconvert\exporters\exporter.py", line 178, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "c:\users\tom\appdata\local\programs\python\python36\lib\site-packages\nbconvert\exporters\exporter.py", line 196, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "c:\users\tom\appdata\local\programs\python\python36\lib\site-packages\nbconvert\exporters\html.py", line 95, in from_notebook_node
    output, resources = super(HTMLExporter, self).from_notebook_node(nb, resources, **kw)
  File "c:\users\tom\appdata\local\programs\python\python36\lib\site-packages\nbconvert\exporters\templateexporter.py", line 300, in from_notebook_node
    nb_copy, resources = super(TemplateExporter, self).from_notebook_node(nb, resources, **kw)
  File "c:\users\tom\appdata\local\programs\python\python36\lib\site-packages\nbconvert\exporters\exporter.py", line 138, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "c:\users\tom\appdata\local\programs\python\python36\lib\site-packages\nbconvert\exporters\exporter.py", line 315, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "c:\users\tom\appdata\local\programs\python\python36\lib\site-packages\nbconvert\preprocessors\base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "c:\users\tom\appdata\local\programs\python\python36\lib\site-packages\nbconvert\preprocessors\execute.py", line 361, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "c:\users\tom\appdata\local\programs\python\python36\lib\site-packages\nbconvert\preprocessors\base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "c:\users\tom\appdata\local\programs\python\python36\lib\site-packages\nbconvert\preprocessors\execute.py", line 385, in preprocess_cell
    raise CellExecutionError.from_cell_and_msg(cell, out)
nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:
------------------
playGame(observe=False);
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mFileNotFoundError[0m                         Traceback (most recent call last)
[1;32m<ipython-input-14-4829a0a02061>[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [0mplayGame[0m[1;33m([0m[0mobserve[0m[1;33m=[0m[1;32mFalse[0m[1;33m)[0m[1;33m;[0m[1;33m[0m[0m
[0m
[1;32m<ipython-input-13-12216cee503d>[0m in [0;36mplayGame[1;34m(observe)[0m
[0;32m      6[0m     [0mmodel[0m [1;33m=[0m [0mbuildmodel[0m[1;33m([0m[1;33m)[0m[1;33m[0m[0m
[0;32m      7[0m     [1;32mtry[0m[1;33m:[0m[1;33m[0m[0m
[1;32m----> 8[1;33m         [0mtrainNetwork[0m[1;33m([0m[0mmodel[0m[1;33m,[0m[0mgame_state[0m[1;33m,[0m[0mobserve[0m[1;33m=[0m[0mobserve[0m[1;33m)[0m[1;33m[0m[0m
[0m[0;32m      9[0m     [1;32mexcept[0m [0mStopIteration[0m[1;33m:[0m[1;33m[0m[0m
[0;32m     10[0m         [0mgame[0m[1;33m.[0m[0mend[0m[1;33m([0m[1;33m)[0m[1;33m[0m[0m

[1;32m<ipython-input-12-d8111a223a7c>[0m in [0;36mtrainNetwork[1;34m(model, game_state, observe)[0m
[0;32m      9[0m     [0mlast_time[0m [1;33m=[0m [0mtime[0m[1;33m.[0m[0mtime[0m[1;33m([0m[1;33m)[0m[1;33m[0m[0m
[0;32m     10[0m     [1;31m# store the previous observations in replay memory[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 11[1;33m     [0mD[0m [1;33m=[0m [0mload_obj[0m[1;33m([0m[1;34m"D"[0m[1;33m)[0m [1;31m#load from file system[0m[1;33m[0m[0m
[0m[0;32m     12[0m     [1;31m# get the first state by doing nothing[0m[1;33m[0m[1;33m[0m[0m
[0;32m     13[0m     [0mdo_nothing[0m [1;33m=[0m [0mnp[0m[1;33m.[0m[0mzeros[0m[1;33m([0m[0mACTIONS[0m[1;33m)[0m[1;33m[0m[0m

[1;32m<ipython-input-6-e73028394228>[0m in [0;36mload_obj[1;34m(name)[0m
[0;32m      3[0m         [0mpickle[0m[1;33m.[0m[0mdump[0m[1;33m([0m[0mobj[0m[1;33m,[0m [0mf[0m[1;33m,[0m [0mpickle[0m[1;33m.[0m[0mHIGHEST_PROTOCOL[0m[1;33m)[0m[1;33m[0m[0m
[0;32m      4[0m [1;32mdef[0m [0mload_obj[0m[1;33m([0m[0mname[0m [1;33m)[0m[1;33m:[0m[1;33m[0m[0m
[1;32m----> 5[1;33m     [1;32mwith[0m [0mopen[0m[1;33m([0m[1;34m'objects/'[0m [1;33m+[0m [0mname[0m [1;33m+[0m [1;34m'.pkl'[0m[1;33m,[0m [1;34m'rb'[0m[1;33m)[0m [1;32mas[0m [0mf[0m[1;33m:[0m[1;33m[0m[0m
[0m[0;32m      6[0m         [1;32mreturn[0m [0mpickle[0m[1;33m.[0m[0mload[0m[1;33m([0m[0mf[0m[1;33m)[0m[1;33m[0m[0m
[0;32m      7[0m [1;33m[0m[0m

[1;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'objects/D.pkl'
FileNotFoundError: [Errno 2] No such file or directory: 'objects/D.pkl'`

**Comment by ravi72munde** [comment]
I'm guessing it has objects folder missing. 
https://github.com/Paperspace/DinoRunTutorial/issues/5
