### ISSUE TITLE
Doubt on javascript code -- usage of `Runner`

### ISSUE THREAD

**Issue by Shekharrajak** [Paperspace/DinoRunTutorial#8]
Thanks for this article. I didn’t understand how did you know `Runner` is for checking the state like current score, gamer running or not, crashed or not, resume, start, …

Is that present in every canvas game? Mean did it work only for chrome://dino ? How can I find out Runner kind of variable to check the game state in other websites?

**Comment by ravi72munde** [comment]
It is specific to this game. I went through the source code of the game to know that Runner object can be used to get these state variables. It will be different for different games, some might not even have any accessible mechanism.
