### ISSUE TITLE
timestep over 100000, have any suggest?

### ISSUE THREAD

**Issue by leeivan1007** [Paperspace/DinoRunTutorial#9]
I rise the batch_size to 64, will want change reward method to up the score.
but before that, want to consult any advice upgrade score, thank you!

![2019-09-06 16-28-42 的螢幕擷圖](https://user-images.githubusercontent.com/14324351/64414057-4833cd80-d0c5-11e9-9ee8-402aa17cccf0.png)

![2019-09-06 16-32-06 的螢幕擷圖](https://user-images.githubusercontent.com/14324351/64414073-51bd3580-d0c5-11e9-83e6-c989a58505d1.png)

**Comment by ravi72munde** [comment]
Increasing batch size shoud be fine but few things need to be considered. 
Increase in bacth size means more data to be processed in a single-go, which might drop your fps.
I can see that your fps is jumping around 4-6 which should be okay. I consitently got an fps of 6-7. 
However, I will be keen to know how you proceed with and your results.
